//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hieu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhmucSP
    {
        public int id { get; set; }
        public string TenDm { get; set; }
        public Nullable<bool> Isdelete { get; set; }
    }
}
