//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hieu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hoadon
    {
        public int Mahd { get; set; }
        public string Hoten { get; set; }
        public string Diachi { get; set; }
        public Nullable<System.DateTime> Ngaygui { get; set; }
        public virtual ICollection<Chitiethoadon> Chitiethoadons { get; set; }
    }
}
