//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hieu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP
    {
        public int Masp { get; set; }
        public string Anh { get; set; }
        public string Ten { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> Ban { get; set; }
        public string Loai { get; set; }
        public Nullable<bool> isdeleted { get; set; }
    }
}
